### PR TITLE
Added waterfall page

### PR DESCRIPTION
**Pull request by mryndzionek**

### CODE REVIEW

**Comment by penfold42** [comment]
sorry for stealing update_display3 while you werent looking :)

**Comment by penfold42** [comment]
Would it help if I added the ability to scroll a section of the display?
That way you'd only need to set 128 pixels

It might event be possible to use the SH1106 native ability to scroll the display (which is really just a start line pointer hack).
Then you'd only need to send 128 pixels and we could just update 1 page (128 bytes) over the I2C bus

**Comment by mryndzionek** [comment]
> Would it help if I added the ability to scroll a section of the display? That way you'd only need to set 128 pixels
> 
> It might event be possible to use the SH1106 native ability to scroll the display (which is really just a start line pointer hack). Then you'd only need to send 128 pixels and we could just update 1 page (128 bytes) over the I2C bus

Yes, sure, go ahead. I don't think this is a bottleneck, but would be also far more elegant.

**Comment by penfold42** [comment]
I've implemented screen scrolling - in all 4 directions in my "blah" branch if you want to take a look.

As we've got 3 PRs open at the moment, Should we wait for the dust to settle before incorporating this ?

**Comment by mryndzionek** [comment]
I rebased this PR to resolve conflicts.

**Comment by penfold42** [comment]
Great - suggestion we merge this now.

I now have a bit of git fiddling to do on my scrolling stuff so would like to rebase it on this.

**Comment by dawsonjon** [comment]
👍

**Comment by penfold42** [comment]
PR #61 submitted

**Pull request merged**
