### PR TITLE
usb controls for level/volume and mute now get applied

### PR DESCRIPTION
**Pull request by penfold42**

### CODE REVIEW

**Comment by penfold42** [comment]
> I think than access to `usb_volume` and `usb_mute` might need locking.

How come ? are usb and rx_dsp on separate cores ?

**Comment by mryndzionek** [comment]
> > I think than access to `usb_volume` and `usb_mute` might need locking.
> 
> How come ? are usb and rx_dsp on separate cores ?

No, but `on_usb_set_mutevol` will, most likely, be called from `usb_audio_device_task`, which is run from an interrupt. `on_usb_audio_tx_ready` only communicates via a ring buffer, which has locking.

**Comment by penfold42** [comment]
There's only 1 writer/1 reader and they're each less than 32 bit objects. Can i be lazy and mark them volatile?

**Comment by mryndzionek** [comment]
> There's only 1 writer/1 reader and they're each less than 32 bit objects. Can i be lazy and mark them volatile?

Yes, sure, we can try, should be atomic.

**Comment by penfold42** [comment]
It seemed to work fine and continues to work fine with volatile.

**Comment by mryndzionek** [comment]
> It seemed to work fine and continues to work fine with volatile.

With concurrency issues it always seems to work fine :wink:

**Comment by penfold42** [comment]
If you still want me to add the locking, is this approach IRQ safe ?
```
sem_acquire_blocking(&usbcontrol_semaphore);
sem_release(&usbcontrol_semaphore);

```

**Comment by mryndzionek** [comment]
> If you still want me to add the locking, is this approach IRQ safe ?
> 
> ```
> sem_acquire_blocking(&usbcontrol_semaphore);
> sem_release(&usbcontrol_semaphore);
> ```

I think a critical section is appropriate in this case: https://www.raspberrypi.com/documentation/pico-sdk/high_level.html#group_critical_section

**Comment by mryndzionek** [comment]
Looks good and works okay on Linux :+1:

**Review by mryndzionek — APPROVED** [review]

**Comment by dawsonjon** [comment]
Cheers

**Comment by penfold42** [comment]
oh excellent - thanks for checking that. Does alsamixer behave sensibly?

**Comment by mryndzionek** [comment]
> oh excellent - thanks for checking that. Does alsamixer behave sensibly?

Yes.

**Pull request merged**
