### PR TITLE
Added USB audio streaming support

### PR DESCRIPTION
**Pull request by mryndzionek**
Initial USB audio streaming support. Some MIT code from GitHub was used.
On Linux, in dmesg this is what should appear:
```
[33708.697590] usb 1-1.3: new full-speed USB device number 32 using xhci_hcd
[33709.031059] usb 1-1.3: New USB device found, idVendor=cafe, idProduct=4010, bcdDevice= 1.00
[33709.031066] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[33709.031070] usb 1-1.3: Product: PicoRX
[33709.031073] usb 1-1.3: Manufacturer: dawsonjon
[33709.031075] usb 1-1.3: SerialNumber: 123456
```

Limitations and things to think about:
 - USB logging was disabled
 - streaming is constantly enabled, as the used library doesn't support graceful deinitialization
 - PWM audio is not turned off while streaming. A mute option should probably be added.

On Linux easiest way to listen to the audio is:
```sh
arecord -f S16_LE -r15650 | aplay -f S16_LE -r15650
```

### CODE REVIEW

**Comment by mryndzionek** [comment]
I'm surprised I don't see a performance impact of this. Either TinyUSB is so efficient (uses DMA etc.), or our time measurement doesn't account for time spent in interrupts (doubt it, as it uses hardware timer).

**Comment by dawsonjon** [comment]
Thanks!

**Comment by mryndzionek** [comment]
One unrelated questions, the map with FT8 callsigns. GridTracker was used to create the map? I don't use Windows, so looking for alternatives.

**Comment by dawsonjon** [comment]
I have just been using https://pskreporter.info/

**Comment by mryndzionek** [comment]
> I have just been using https://pskreporter.info/

I have a list, a file of callsigns. How to show all of them on a map?

**Pull request merged**
