### PR TITLE
Added audio denoiser

### PR DESCRIPTION
**Pull request by mryndzionek**
This is the first version. Exposing some more settings might be needed. The frame length is not ideal. Should be around 30ms, but is now ~8ms. Further adjusting FFT size might be desirable (if CPU power allows). In order to avoid ifdef-hell the denoiser option in menu is not removed on platfroms that don't support it (RISC-V).

### CODE REVIEW

**Comment by mryndzionek** [comment]
> This is the first version. Exposing some more settings might be needed. The frame length is not ideal. Should be around 30ms, but is now ~8ms. Further adjusting FFT size might be desirable (if CPU power allows). In order to avoid ifdef-hell the denoiser option in menu is not removed on platfroms that don't support it (RISC-V).

**Comment by dawsonjon** [comment]
Cool!

**Comment by asflorenciotec** [comment]
Heva a background hum noise on audio 600Hz.

**Comment by mryndzionek** [comment]
> There is a continuous noise of approximately 400Hz in the background throughout the tuning, is this correct?

With the denoiser enabled, or also without? Could you send a sample WAV file?

**Comment by asflorenciotec** [comment]
I will send a recorded audio

Em sex., 1 de nov. de 2024, 09:56, mryndzionek ***@***.***>
escreveu:

**Pull request merged**
