### PR TITLE
U8g2 integration

### PR DESCRIPTION
**Pull request by mryndzionek**
Added u8g2 library and integrated it into our display driver, so that (hopefully) nothing breaks and migration can be performed gradually. Revamped the main/original page using the library. To build, download/clone [u8g2](https://github.com/olikraus/u8g2) into `external`  subdirectory (might be worth adding it as a submodule). Rebuilding from scratch (removing whole CMake build directory) is advised.

### CODE REVIEW

**Comment by mryndzionek** [comment]
Here is a preview of the new page:
out

**Comment by penfold42** [comment]
Looks great !

You should PR the screendump code. Could be handy for maintaining the doco

**Comment by mryndzionek** [comment]
> Looks great !
> 
> You should PR the screendump code. Could be handy for maintaining the doco

BTW, could you take a look at the scrolling adjustment? It was late yesterday and I might have missed something.

**Comment by penfold42** [comment]
Code looks ok and seems to work ok.
I got the phone out again to check on the "fun'.

**Comment by penfold42** [comment]
One other thing - I had to remove -Wall or it wouldn't compile

**Comment by mryndzionek** [comment]
> One other thing - I had to remove -Wall or it wouldn't compile

Compiles cleanly on my side. Errors in u8g2?

**Comment by mryndzionek** [comment]
I added the code needed to record and decode a screendump. Here is another one :smile: 
cutecom

**Comment by penfold42** [comment]
Yep - not your codeOn 4 Oct 2024, at 6:11 PM, mryndzionek ***@***.***> wrote:﻿

One other thing - I had to remove -Wall or it wouldn't compile

Compiles cleanly on my side. Errors in u8g2?

**Comment by MrSVCD** [comment]
Is there a "better" 7 segment font?
The one you are showing gives me shivers down my spine.
"Better" is of course a matter of taste.
My solution to my shivers would be a font that doesn't lean.

**Comment by mryndzionek** [comment]
> Is there a "better" 7 segment font? The one you are showing gives me shivers down my spine. "Better" is of course a matter of taste. My solution to my shivers would be a font that doesn't lean.

LOL Fonts are details. I had to cobble together a font which was monospace and with specific width and height.

**Comment by mryndzionek** [comment]
Is this better?
cutecom_000000

**Comment by mryndzionek** [comment]
This, I think, is even better:
cutecom_000001

**Comment by mryndzionek** [comment]
Okay, I think I've found something that behaves nicely and looks better:
cutecom_000000

**Comment by dawsonjon** [comment]
Cool, love the new look!

**Pull request merged**
