### PR TITLE
Made the display draw more pre-emptive

### PR DESCRIPTION
**Pull request by mryndzionek**
This is just a proposal. Tried to make it as pretty as possible.This essentially adds "pre-emption" point after every display page transfer. I would add some more sophisticated button event handling, but I can't do it because of more than 50ms blocking in `ssd1306_show`.

### CODE REVIEW

**Comment by penfold42** [comment]
Is 50ms what it was or is it 50ms per page now ?

**Comment by mryndzionek** [comment]
> Is 50ms what it was or is it 50ms per page now ?

No measurements yet, but should be now ~(50/8)ms per page.

**Comment by mryndzionek** [comment]
I unified the encoder handling with the other events. Fairly large changes. Hope there are no regressions. Testing is appreciated. The only potential, sort of, issue I noticed is waterfall tearing when encoder rotated. Actually looks kind of cool, so might be a feature not a bug :smile: . We can now control how fast the encoder response is. In this PR it is set to fairly fast - noticeable in menu.

**Comment by dawsonjon** [comment]
Hi, would you mind holding off on this for now? I have a branch in the pipeline to add support for tft display, cat control and usb audio. I've changed the approach slightly and I'm not quite sure how this is going to fit.

**Comment by mryndzionek** [comment]
> Hi, would you mind holding off on this for now? I have a branch in the pipeline to add support for tft display, cat control and usb audio. I've changed the approach slightly and I'm not quite sure how this is going to fit.

This is just an experiment, so no worries.

**Pull request closed without merging**
