### PR TITLE
Added audio de-emphasis

### PR DESCRIPTION
**Pull request by mryndzionek**

### CODE REVIEW

**Comment by penfold42** [comment]
cool!

could the de-emphasis settings be stored in 2 bits of rx_features  (next to flag_enable_auto_notch)

**Comment by mryndzionek** [comment]
> cool!
> 
> could the de-emphasis settings be stored in 2 bits of rx_features (next to flag_enable_auto_notch)

Done.

**Comment by penfold42** [comment]
super quick! 
I should probably move my oled_contrast setting into idx_hw_setup too

**Comment by dawsonjon** [comment]
Thanks, great work as usual!
The 50us and 75us settings have a break-in frequency of 3.1 and 2.1 kHz which is quite close to the audio cutoff frequency. I wonder if different settings would be better for narrow band modes? I had a quick search to see if there was any info on this, but couldn't find anything definitive, do you know of any good references?

**Comment by mryndzionek** [comment]
> Thanks, great work as usual! The 50us and 75us settings have a break-in frequency of 3.1 and 2.1 kHz which is quite close to the audio cutoff frequency. I wonder if different settings would be better for narrow band modes? I had a quick search to see if there was any info on this, but couldn't find anything definitive, do you know of any good references?

Hmm, I only see a KiwiSDR thread [here](https://forum.kiwisdr.com/index.php?p=/discussion/2820/v1-577-nbfm-and-am-ssb-de-emphasis). "Designing"  the filter is not complicated, so we might even add `tau` as input parameter.

**Pull request merged**
