### PR TITLE
 Changed the display memory addressing mode to be able to support different display controllers

### PR DESCRIPTION
**Pull request by mryndzionek**
I would like to use bigger, 1.3 inch OLED display and those displays are mostly based on SH1106 controllers, which are mostly compatible with the SSD1306 controllers, but don't support currently used addressing mode. This different addressing mode requires additional buffer, but I think it's worth it.

BTW, I've tested the u8g2 library with those I2C OLED displays on RP2040. Integrating this library would allow for many more displays being supported and more fancy UI would be possible. Let me know what you think. I have some spare cycles, so would be able to work on this.

### CODE REVIEW

**Comment by dawsonjon** [comment]
Cool, that's really neat! Does this change allow both SH1106 and SSD1306 display to be used without modification? Were you able to test with SSD1306, or should I test for backwards compatibility?

I'm intrigued by the u8g2 library suggestion. Would this allow a single build to support multiple displays, or would it need a compile time option?

**Comment by mryndzionek** [comment]
I've forced pushed some improvements - no need for additional buffer now.

> Cool, that's really neat! Does this change allow both SH1106 and SSD1306 display to be used without modification? Were you able to test with SSD1306, or should I test for backwards compatibility?
> 

I've tested with SSD1306 for back compatibility. For a SH1106 you need to define `DISP_CTRL_SH1106` e.g. in CMakeLists.txt.

> I'm intrigued by the u8g2 library suggestion. Would this allow a single build to support multiple displays, or would it need a compile time option?

Normally this is done at compile time. Runtime might also be possible.

**Comment by mryndzionek** [comment]
I've been also experimenting with bigger TFT displays. Framebuffer in full color is too big to fit RP2040's RAM, but I managed to use monochrome mode for a 480x320 display: https://github.com/mryndzionek/rp2040_pico_sdk_playground?tab=readme-ov-file#rpi_lcd_test

**Comment by dawsonjon** [comment]
Cool

**Comment by dawsonjon** [comment]
Thanks!

**Comment by penfold42** [comment]
This fails for me in vscode (and warnings are errors...)
```
C:/Users/damia/PicoRX/ssd1306.c:126:10: error: the comparison will always evaluate as 'true' for the pointer operand in 'p->mbuffer + -1' must not be NULL [-Werror=address]
  126 |     if ( p->mbuffer -1 )
      |          ^
```

I have a PR coming which fixes it

**Comment by mryndzionek** [comment]
> the comparison will always evaluate as

Interesting. Which gcc version (`arm-none-eabi-gcc --version`)?

**Comment by mryndzionek** [comment]
I guess this can be changed to:
```c
    if (p->bufsize > 0)
    {
        free(p->buffer - 1);
    }
```

**Comment by penfold42** [comment]
arm-none-eabi-gcc (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)) 13.2.1 20231009

installed via vscode pi pico addin

have a peek at #24 - the latest fix makes each page 129 bytes long to make room for the 0x40

**Comment by mryndzionek** [comment]
> arm-none-eabi-gcc (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)) 13.2.1 20231009

Wow. Bleeding edge. Not always a good thing. I heard there are regressions for e.g. RP2350. I have `10.3.1` installed via `apt`.

**Comment by penfold42** [comment]
:)

C:\Users\\PicoRX>apt-get install stuff
'apt-get' is not recognized as an internal or external command,
operable program or batch file.

**Pull request merged**
