### PR TITLE
Some adjustments around FFT calculation + minor fixes

### PR DESCRIPTION
**Pull request by mryndzionek**
I know that some people are not huge fans of using const LUTs, but saves some memory and often compute.
Also added few small fixes/adjustments. time_us_32() overflows after more than an hour, so is enough for measuring momentary utilization.

### CODE REVIEW

**Comment by dawsonjon** [comment]
Thanks, this looks good. The changes to the time types look good. The fft window change looks OK too, I don't have a problem with const LUTs. I have used them all over the place. I wonder if it would have been easier to declare.the window as a static const? This would have had most of the benefits, i.e. moving the table into static memory rather than on the stack, and only requiring the table to be calculated once, the first time it's called. 

However, I think this might not matter in the longer term, I think that this code will disappear altogether. I'm planning to move over to frequency domain filtering (it's on the testing branch), which means that I'm now generating FFTs in real time using fixed point. This makes the much slower floating point FFT redundant since the data exists already.

**Comment by mryndzionek** [comment]
> it would have been easier to declare.the window as a static const?

I'm not sure if I understand... It is `static const`, no?

> I'm planning to move over to frequency domain filtering (it's on the testing branch), which means that I'm now generating FFTs in real time using fixed point. 

This is great. Was thinking about that. Is it still 256-bin and at 500kSps?

**Comment by dawsonjon** [comment]
I'm still decimating first using a cic filter, but I'm using a fixed decimation rate of 16 which makes things much simpler. I'm using a windowed overlap add. The forward fft is 256 points 32.25kHz, and I retain the central 128 points then inverse fft giving 16.125kHz into the demodulator. In both cases the bins are 122Hz wide. 
I have made it so the filter bandwidth can be adjusted on the fly, and it should open up possibilities for more sophisticated processing in the frequency domain too.

**Comment by mryndzionek** [comment]
> However, I think this might not matter in the longer term, I think that this code will disappear altogether. 

So maybe I'll remove the window commit. Would be good to have the other two merged.

**Comment by dawsonjon** [comment]
Yes, sounds good 👍

**Comment by mryndzionek** [comment]
Okay, I removed the commit.

**Comment by dawsonjon** [comment]
Cheers!

**Pull request merged**
